version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
      - REDIS_URL=redis://redis_cache:6379/0
    depends_on:
      - redis_cache
    restart: always

  redis_cache:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

networks:
  default:
    name: savemoney_network